### ISSUE TITLE
Restrict default information shared with every event

### ISSUE THREAD

**Issue by RichardPK** [benawad/expo-mixpanel-analytics#3]
Awesome package - thank you for making it!

I was wondering if it's possible to limit the default information that is being sent with every event being tracked by the package?

As our Mixpanel account is tied to a specific app, the ``` app_id, app_version``` information is just a distraction.

**Comment by benawad** [comment]
Happy to merge a pull request if you want to implement a way to do that.

**Comment by RichardPK** [comment]
Hey @benawad nice will take a look when I get chance. Cheers
